# Generated by Django 3.2.16 on 2022-12-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardediter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PictureTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/picture_templates/', verbose_name='Шаблон')),
            ],
        ),
    ]
